spring:
    jpa:
        generate-ddl: true
        database: h2
        show-sql: true
        hibernate:
            ddl-auto: create-drop
    datasource:
        name: accounts
        url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS accounts
        initialization-mode: always
    h2:
        console:
            enabled: true
            path: /console
    application:
        name: accounts
    sql:
        init:
            data-locations: classpath:/sql/data.sql
            mode: always
server:
    port: 8082
management:
    endpoints:
        web:
            exposure:
                include: prometheus,health,info,metrics
    security:
        enabled=false
    endpoint:
        health:
            show-details: always
    web:
        server:
            request:
                autotime:
                    percentiles: 0.9, 0.95
                metric-name: response_time
    #metrics:
    #    distribution:
    #        percentiles-histogram:
    #            api:
    #                request:
    #                    duration: true
    #        percentiles:
    #            api:
    #                request:
    #                    duration: 0.9, 0.95
    #        slo:
    #            api:
    #                request:
    #                    duration: 1ms, 10ms, 100ms, 1s, 5s, 10s

