spring:
    jpa:
        generate-ddl: true
        database: h2
        show-sql: true
        hibernate:
            ddl-auto: create-drop
    datasource:
        name: accounts
        url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS accounts
        initialization-mode: always
    h2:
        console:
            enabled: true
            path: /console
    application:
        name: accounts
    sql:
        init:
            data-locations: classpath:/sql/data.sql
            mode: always
server:
    port: 8082
management:
    endpoints:
        web:
            exposure:
                include: prometheus,health,info,metric
    security:
        enabled=false
    endpoint:
        health:
            show-details: always
            probes:
                enabled: true
            group:
                liveness:
                    include:
                        - livenessState
                readiness:
                    include:
                        - readinessState
                        - accounts
            enabled: true